before_deploy: cd client
language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep-history: true
  on:
    branch: master

