deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  language: node_js
  node_js:
    - "iojs"
    - "7"
  before_script: cd client
on:
  branch: master
