before_script:
  - cd client
  - github_token: $GITHUB_TOKEN
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  
  local_dir: client/build
  on:
    branch: master
